**# Spam Email Classifier**

## Objective
**The objective of this project is to classify emails/messages as spam or not spam using Machine Learning techniques. This model is trained using a dataset of messages and predicts whether a new message is spam or genuine.**

In [1]:
import pandas as pd
import numpy as np

In [2]:
import sklearn
print("Libraries imported successfully")

Libraries imported successfully

**importing dataset**

In [3]:
import urllib.request

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
urllib.request.urlretrieve(url, "spam.csv")

print("Dataset downloaded successfully")

Dataset downloaded successfully

In [4]:
data = pd.read_csv("spam.csv", sep="\t", header=None)
data.columns = ["label", "message"]

data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
print(data.shape)
data.info()

(5572, 2)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

**converting labels into numbers**

In [6]:
data["label"] = data["label"].map({"ham": 0, "spam": 1})

data.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

**separating labels**

In [7]:
X = data["message"]
y = data["label"]

print(X.head())
print(y.head())

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: message, dtype: object
0    0
1    0
2    1
3    0
4    0
Name: label, dtype: int64

**vectorization**

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(X)

**separating training and testing dataset**

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Data split successful")

Data split successful

**training model using NAIVE BAYES ALGORITHM**

In [10]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

print("Model trained successfully")

Model trained successfully

**checking model accuracy**

In [11]:
from sklearn.metrics import accuracy_score

prediction = model.predict(X_test)

accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy)

Accuracy: 0.9856502242152466

**making our own spam checker**

In [12]:
message = ["Congratulations! You won a free iPhone. Click now!"]

message_count = cv.transform(message)

prediction = model.predict(message_count)

if prediction[0] == 1:
    print("Spam Email")
else:
    print("Not Spam Email")

Spam Email

In [13]:
message = ["Hey, are we meeting tomorrow?"]

message_count = cv.transform(message)

prediction = model.predict(message_count)

if prediction[0] == 1:
    print("Spam Email")
else:
    print("Not Spam Email")

Not Spam Email